name: Bug Fix
description: 不具合を修正するIssue Type
title: "[Bug Fix]: "
labels:
  - "Bug Fix"

body:
  - type: textarea
    attributes:
      label: Related Links
      description: 関連する Issue や、 Slack のリンクを記載する

  - type: textarea
    attributes:
      label: Figma Design
      description: FigmaのDesignリンクを記載する。

  - type: textarea
    attributes:
      label: Bug Description
      description: 現状のバグ状況を記載する。記載方法は、誰が、何をすると、何が起きるか、を記載する。
                   暫定対応と恒久対応がある場合、暫定対応をBugとしてIssueを作成し、恒久対応をRefactoringのIssueで作成して対応する。（この対応で合わない場合は、柔軟に対応する） 

  - type: textarea
    attributes:
      label: Image
      description: DesignやCaptureを張る場合、こちらに記載する。

  - type: textarea
    attributes:
      label: 再現方法
      description: どうしたら、再現されるかの詳細手順を箇条書きで記載する。（又は、動画があればそちらを添付する。）

  - type: textarea
    attributes:
      label: 改善後仕様 (Acceptance Criteria) 
      description: 修正後の要件を記述する。記載方法はAcceptance Criteriaと同じにする。

  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する

  - type: textarea
    attributes:
      label: Feature Flag
      description: Feature Flagの名称を記載する

  - type: textarea
    attributes:
      label: Cause (Reporting)
      description: Bugが起きた原因を詳細に記載する。Bugの内容は微小なものでも必ず、Sprint Retrospectiveにて共有する。Formatは以下の通り。

  - type: textarea
    attributes:
      label: Solution (Reporting)
      description: どうやって解決したかを記載する。

  - type: textarea
    attributes:
      label: Long-term Solution (Reporting)
      description: 長期的、または恒久対応などが必要であれば記載する。（例えば、Operationの改善など）
