name: Epic
description: 複数のUser StoryをまとめるIssue Type。User Storyより一つ上の階層になる
title: "[Epic]: "
labels:
  - "Epic"

body:
  - type: textarea
    attributes:
      label: Parent Issues
      description: Epicの親にあたるIssueを記載する。

  - type: textarea
    attributes:
      label: Child Issues
      description: 子Issue (User Story) を記載する。

  - type: textarea
    attributes:
      label: Others Issues or Links
      description: 関連するその他のIssueや、 リンクを記載する

  - type: textarea
    attributes:
      label: Description
      description: Epicの概要を記載する

  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する

  - type: textarea
    attributes:
      label: Feature Flag
      description: Feature Flagの名称を記載する
