name: Epic
description: 複数のUser StoryをまとめるIssue Type。User Storyより一つ上の階層になる
title: "[Epic]: "
labels:
  - "Epic"

body:

  - type: textarea
    attributes:
      label: Figma Design
      description: FigmaのDesignリンクを記載する。

  - type: textarea
    attributes:
      label: Others Issues or Links
      description: 関連するその他のIssueや、 リンクを記載する

  - type: textarea
    attributes:
      label: Description (Who, what, why)
      description: Epicの概要をWho, what, whyのFormatで記載する

  - type: textarea
    attributes:
      label: Image
      description: DesignやCaptureを張る場合、こちらに記載する。

  - type: textarea
    attributes:
      label: When/Deploy
      description: いつまでにReleaseされるべきか、また、どの環境にDeployされるべきかを記載する。

  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する

  - type: textarea
    attributes:
      label: Feature Flag
      description: Feature Flagの名称を記載する
