name: Bug Fix
description: Feature Flagを削除するためのIssue Type
title: "test"
labels:
  - "Feature Flag Removal"

body:
  - type: textarea
    attributes:
      label: Related links
      description: 関連する Issue や、 Slack のリンクを記載する
