name: Feature Flag Removal
description: Feature Flagの削除を行うIssue Type
labels:
  - "Feature Flag Removal"
body:
  - type: textarea
    attributes:
      label: Related Links
      description: 関連する Issue や、 Slack のリンク、リファクタリングの理由を記載する

  - type: textarea
    attributes:
      label: Description
      description: 概要を記載する。（必要であれば）

  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する

  - type: textarea
    attributes:
      label: Feature Flag
      description: Feature Flagの名称を記載する
