name: Spike
description: Spikeを行う時のIssue Type。
labels:
  - "Spike"
body:
  - type: textarea
    attributes:
      label: Related Links
      description: 関連する Issue や、 Slack のリンクを記載する。

  - type: textarea
    attributes:
      label: Description
      description: Spikeの内容と理由を記載する。詳細はこちら参照 https://docs.google.com/presentation/d/1-z6B3tyji7bVegMOyEtl__nOQJrHSETmSV6Ti1NTQxU/edit#slide=id.g26536243de2_0_176

  - type: textarea
    attributes:
      label: Output
      description: 調査結果をこちらに記載し、Team全体、またはProduct Ownerへ共有する。


  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する

  - type: textarea
    attributes:
      label: Cause (Reporting)
      description: 障害が起きた原因を詳細に記載する。（5W1H, 5Wなど参照）

  - type: textarea
    attributes:
      label: Solution (Reporting)
      description: どうやって解決したかを記載する。

  - type: textarea
    attributes:
      label: Long-term Solution (Reporting)
      description: 長期的、または恒久対応などが必要であれば記載する。（例えば、Operationの改善など）
