name: Task
description: Userに影響はなく、技術・開発レベルで行う作業を総合的に表すIssue Type
labels:
  - "Task"

body:
  - type: textarea
    attributes:
      label: Related Links
      description: 関連する Issue や、 Slack のリンクを記載するaaaa

  - type: textarea
    attributes:
      label: Requirements
      description: 必要な要件を記述する

  - type: textarea
    attributes:
      label: Task List
      description: 細分化したタスクの完了条件を記述する
      placeholder: |
        - [ ] ~~ をテストする
      value: |
        - [ ] 

  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する
  - type: textarea
    attributes:
      label: Feature Flag
      description: Feature Flagの名称を記載する
