name: User Story
description: 新機能の開発a
labels:
  - "User Story 🧠"

body:
  - type: textarea
    attributes:
      label: Parent Issues
      description: User Storyの親にあたるIssueを記載する。

  - type: textarea
    attributes:
      label: Child Issues
      description: 子Issue (User Story Task等) を記載する。

  - type: textarea
    attributes:
      label: Others Issues or links
      description: 関連するその他のIssueや、 リンクを記載する

  - type: textarea
    attributes:
      label: User Story
      description: User Storyは一行で 誰が(Who) 何をしたいか(What) なぜしたいか(Why) の項目を記載する

  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: |
        下記を満たすように記載する
        - Scenario: シナリオのタイトル
        - Given: シナリオの前提条件 (input)
        - When: シナリオの実行条件
        - Then: シナリオの結果 (output)
        - And: その他の条件
      value: |
        - [ ] Scenario:
        Given:
        When:
        Then:
        And:
  - type: textarea
    attributes:
      label: Notes
      description: 補足事項を記載する
  - type: textarea
    attributes:
      label: Feature Flag
      description: Feature Flagの名称を記載する
